Update shapefile.cpp
add tempate so that it compiles under RHEL 6 - corrects this issue:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb 
rm -f *.o shptest shpcreate shpadd shpdump shprewind dbfcreate dbfadd dbfdump shptreedump  libshp.a 
cc -g -Wall -fPIC -c shpopen.c
cc -g -Wall -fPIC -c safileio.c
cc -g -Wall -fPIC shpcreate.c shpopen.o safileio.o  -o shpcreate
cc -g -Wall -fPIC shpadd.c shpopen.o safileio.o  -o shpadd
cc -g -Wall -fPIC shpdump.c shpopen.o safileio.o  -o shpdump
cc -g -Wall -fPIC shprewind.c shpopen.o safileio.o  -o shprewind
cc -g -Wall -fPIC -c dbfopen.c
cc -g -Wall -fPIC dbfcreate.c dbfopen.o safileio.o  -o dbfcreate
cc -g -Wall -fPIC dbfadd.c dbfopen.o safileio.o  -o dbfadd
cc -g -Wall -fPIC dbfdump.c dbfopen.o safileio.o  -o dbfdump
cc -g -Wall -fPIC -c shptree.c
cc -g -Wall -fPIC shptreedump.c shptree.o shpopen.o safileio.o  \
		-o shptreedump
cc -g -Wall -fPIC shptest.c shpopen.o safileio.o  -o shptest
ar r libshp.a shpopen.o dbfopen.o safileio.o shptree.o 
ar: creating libshp.a
checking for main() in -lshp... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling shape_object.cpp
shape_object.cpp: In static member function ‘static void shp::shape_object::define(VALUE)’:
shape_object.cpp:274: error: ‘template<class T> class shp::base’ used without template parameters
make: *** [shape_object.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.1.2@fcc-smra/gems/shp-0.0.3 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.1.2@fcc-smra/extensions/x86_64-linux/2.1.0/shp-0.0.3/gem_make.out
An error occurred while installing shp (0.0.3), and Bundler cannot continue.
Make sure that `gem install shp -v '0.0.3'` succeeds before bundling.